name: Ruby

on:
  schedule:
    - cron: '10 * * * *'
jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: CHECK IP address
      run: |
        curl ifconfig.me
        gem install brakeman
        brakeman
      
